### ISSUE TITLE
Jade Release

### ISSUE THREAD

**Issue by wjwwood** [ros/filters#10]
@jonbinney did you mention you could release this? :wink:

**Comment by jonbinney** [comment]
Suurrreee.... I just compiled under jade and all tests passed. Will release nowish

**Comment by jonbinney** [comment]
Released. rosdistro PR: https://github.com/ros/rosdistro/pull/8040

Will close this issue after everything builds on the farm.

**Comment by jonbinney** [comment]
It looks like the buildfarm still hasn't built this: http://www.ros.org/debbuild/jade.html

@wjwwood is the buildfarm going slow for some reason?

**Comment by tfoote** [comment]
The farm's quite busy right now, we released several low level packages into jade, including catkin, so there's over 800 jobs in the queue. 

Additionally as this is a first time release it will not run until the job is generated for it when the farm reconfigures overnight. So it's going to be a while. Hopefully some time tomorrow.

**Comment by jonbinney** [comment]
Is there a page that shows the build queue for the jade buildfarm? The only link I can find for the jade buildfarm is http://www.ros.org/debbuild/jade.html which doesn't give a sense of how many jobs are pending.

**Comment by wjwwood** [comment]
http://jenkins.ros.org

Left hand column.

**Comment by jonbinney** [comment]
Thanks!

**Comment by jonbinney** [comment]
Built and is now in shadow fixed.
