### ISSUE TITLE
Badly formed XML file 'default_plugins.xml'

### ISSUE THREAD

**Issue by ernestmc** [ros/filters#13]
XML definition forbids `<` inside strings and should be escaped by `&lt;` Using Python I get errors parsing this file.

E.g: https://github.com/ros/filters/blob/hydro-devel/default_plugins.xml#L3

See: http://www.w3schools.com/xml/xml_syntax.asp

**Comment by jonbinney** [comment]
Hi @ernestmc , thanks for reporting this - any chance you could create a pull request fixing it?
