### ISSUE TITLE
ROS2 port

### ISSUE THREAD

**Issue by vandanamandlik** [ros/filters#21]
We are working on laser assembler porting to ROS2 but its dependent on Filters package.
So we have taken up this package for porting.

**Comment by vandanamandlik** [comment]
Hi,
We have done with the porting of filters package to ROS2 and send a PR.
https://github.com/ros/filters/issues/24

Waiting for the review and suggestion for the same.

**Comment by jonbinney** [comment]
Closing this since there this package now works on ros2 and has been released.
