### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by peci1** [ros/filters#36]
See the build status of https://github.com/ros/filters/pull/35 . CI could not install catkin :(

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/catkin-installation-fails-in-ci-docker/15038/1

**Comment by peci1** [comment]
Solved by https://discourse.ros.org/t/build-ci-failures-with-ros-testing-repository-enabled/15006.
