### ISSUE TITLE
Release a ros package like ros-version-filters?

### ISSUE THREAD

**Issue by felixf4xu** [ros/filters#78]
Hi,

I'm using Ubuntu and I can't find this package in `apt search`.

Almost all other packages I need to install can be find in apt search, this might be the only one that I need to build from source, so a apt package should be nice.

**Comment by jonbinney** [comment]
Hi felix - if you need filters (or a bunch of other ROS packages not in the standard ubuntu repos), install from the OSRF repo: https://docs.ros.org/en/jazzy/Installation.html

Once you add that apt repo, you should be able to apt search and find the filters package.
